name: Docker Package
on:
  push:
    branches:
        - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  
    - uses: martinbeentjes/npm-get-version-action@master
      id: package-version
      with:
        path: ./
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: hzsq
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: hz2
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: NPM build
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - run: npm install && npm run build  
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          hzsq/pub.css:${{ steps.package-version.outputs.current-version}}
          hzsq/pub.css:latest
          ghcr.io/hz2/pub_css:${{ steps.package-version.outputs.current-version}}
          ghcr.io/hz2/pub_css:latest

    - run: curl -X POST "${{ secrets.TG_URL }}" -d "chat_id=${{ secrets.TG_CHAT_ID }}&text=pub.css%20%E7%9A%84%20docker%E5%8C%85%20%E5%8F%91%E5%B8%83%E6%88%90%E5%8A%9F%EF%BC%81"
